openapi: 3.0.0
paths:
  /rates:
    get:
      summary: Returns rates.
      description: Returns currency rates.
      responses:
        '200':    # status code
          description: Currency rates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RatesResponse'

components:
  schemas:
    RatesResponse:
      type: object
      properties:
        base:
          $ref: '#/components/schemas/Currency'
        rates:
          type: object
          additionalProperties:
            type: number
          example:
            USD: 91.42
            RUB: 1
    Currency:
      type: string
      enum:
        - "RUB"
        - "CNY"
        - "EUR"
        - "USD"
        - "GBP"
