openapi: 3.0.0
components:
  schemas:
    RatesResponse:
      type: object
      properties:
        base:
          $ref: '#/components/schemas/Currency'
        rates:
          type: object
          additionalProperties:
            type: number
          example:
            USD: 91.42
            RUB: 1
    Currency:
      type: string
      enum:
        - "RUB"
        - "CNY"
        - "EUR"
        - "USD"
        - "GBP"
