openapi: 3.0.4
info:
  title: Banking - Common
  description: This is a OpenAPI 3.0 specification that describes common banking system components.
  version: 1.0.0
components:
  schemas:
    Currency:
      type: string
      enum:
        - "USD"
        - "RUB"
        - "CNY"
        - "EUR"
        - "GBP"
      example: USD
    CurrencyAmount:
      type: number
      example: 1234.56
  responses:
    InvalidQuery:
      description: Invalid query with cause message.
      content:
        application/json:
          schema:
            title: InvalidQueryResponse
            type: object
            properties:
              message:
                type: string
                example: Property 'abc' must be positive number
            required:
              - message
