openapi: 3.0.4
info:
  title: Banking - Common
  description: This is a OpenAPI 3.0 specification that describes common banking system components.
  version: 1.0.0
components:
  schemas:
    Currency:
      type: string
      enum:
        - "USD"
        - "RUB"
        - "CNY"
        - "EUR"
        - "GBP"
      example: USD
    CurrencyAmount:
      type: number
      example: 1234.56
    RatesResponse:
      type: object
      properties:
        base:
          $ref: '#/components/schemas/Currency'
        rates:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/CurrencyAmount'
          example:
            USD: 31.42
            RUB: 1
      required:
        - base
        - rates
  responses:
    InvalidRequest:
      description: Invalid request with cause message.
      content:
        application/json:
          schema:
            title: InvalidRequestResBody
            type: object
            properties:
              message:
                type: string
                example: Property 'abc' must be positive number
