openapi: 3.0.4
info:
  title: Banking - Common
  description: This is a OpenAPI 3.0 specification that describes common banking system components.
  version: 1.0.0
components:
  schemas:
    Currency:
      type: string
      enum:
        - "USD"
        - "RUB"
        - "CNY"
        - "EUR"
        - "GBP"
    CurrencyAmount:
      type: number
      example: 1234.56
    RatesResponse:
      type: object
      properties:
        base:
          $ref: '#/components/schemas/Currency'
        rates:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/CurrencyAmount'
          example:
            USD: 31.42
            RUB: 1
