/*
 * Sample API
 * Valuable description
 *
 * OpenAPI spec version: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package edu.tinkoff.spring.models;

/**
 * Gets or Sets Currency
 */
// @JsonAdapter(Currency.Adapter.class)
public enum Currency {
  // @SerializedName("RUB")
  RUB("RUB"),
  // @SerializedName("CNY")
  CNY("CNY"),
  // @SerializedName("EUR")
  EUR("EUR"),
  // @SerializedName("USD")
  USD("USD"),
  // @SerializedName("GBP")
  GBP("GBP");

  private String value;

  Currency(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Currency fromValue(String input) {
    for (Currency b : Currency.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  /*public static class Adapter extends TypeAdapter<Currency> {
    @Override
    public void write(final JsonWriter jsonWriter, final Currency enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public Currency read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return Currency.fromValue((String)(value));
    }
  }*/
}
