spring:
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:9876/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

services:
  timeout: 5

  converter:
    url: ${CONVERTER_URL}/convert?from={from}&to={to}&amount={amount}

  keycloak:
    url:
      get: ${KEYCLOAK_URL:}/realms/${KEYCLOAK_REALM:}/protocol/openid-connect/token
      validate: ${KEYCLOAK_URL:}/realms/${KEYCLOAK_REALM:}/protocol/openid-connect/certs
    client:
      id: ${CLIENT_ID:}
      secret: ${CLIENT_SECRET:}
