/*
 * Sample API
 * Valuable description
 *
 * OpenAPI spec version: 0.1.9
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package edu.tinkoff.model;

import java.util.Objects;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

/**
 * RatesResposne
 */

// @javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-02-19T22:07:42.390203900+03:00[Europe/Moscow]")

public class RatesResposne {
  // @SerializedName("base")
  private Currency base = null;

  // @SerializedName("rates")
  private Map<String, BigDecimal> rates = null;

  public RatesResposne base(Currency base) {
    this.base = base;
    return this;
  }

   /**
   * Get base
   * @return base
  **/
  // @Schema(description = "")
  public Currency getBase() {
    return base;
  }

  public void setBase(Currency base) {
    this.base = base;
  }

  public RatesResposne rates(Map<String, BigDecimal> rates) {
    this.rates = rates;
    return this;
  }

  public RatesResposne putRatesItem(String key, BigDecimal ratesItem) {
    if (this.rates == null) {
      this.rates = new HashMap<String, BigDecimal>();
    }
    this.rates.put(key, ratesItem);
    return this;
  }

   /**
   * Get rates
   * @return rates
  **/
  // @Schema(example = "{\"USD\":91.42,\"RUB\":1}", description = "")
  public Map<String, BigDecimal> getRates() {
    return rates;
  }

  public void setRates(Map<String, BigDecimal> rates) {
    this.rates = rates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RatesResposne ratesResposne = (RatesResposne) o;
    return Objects.equals(this.base, ratesResposne.base) &&
        Objects.equals(this.rates, ratesResposne.rates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(base, rates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RatesResposne {\n");

    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    rates: ").append(toIndentedString(rates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
