#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	  CREATE USER $ACCOUNTS_USER WITH PASSWORD '$ACCOUNTS_PWD';
    CREATE DATABASE $ACCOUNTS_DB OWNER $ACCOUNTS_USER;

    CREATE USER $KEYCLOAK_USER WITH PASSWORD '$KEYCLOAK_PWD';
    CREATE DATABASE $KEYCLOAK_DB OWNER $KEYCLOAK_USER;
EOSQL
