services:
  timeout: 5

  currency-rates:
    url: ${RATES_URL}/rates

  keycloak:
    url:
      get: ${KEYCLOAK_URL:}/realms/${KEYCLOAK_REALM:}/protocol/openid-connect/token
      validate: ${KEYCLOAK_URL:}/realms/${KEYCLOAK_REALM:}/protocol/openid-connect/certs
    client:
      id: ${CLIENT_ID:}
      secret: ${CLIENT_SECRET:}
