{{ if .Values.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.name }}
data:
  config-file: |
    {{- with .Values.config.data }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
