name: Build Docker Image

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build
        run: ./gradlew clean build
      - name: Set branch name
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> "$GITHUB_ENV"
      - name: Set branch name on PR trigger
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "BRANCH_NAME=${{ github.head_ref }}" >> "$GITHUB_ENV"
      - name: Set Docker image name and image tag
        run: |
          echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/ci-cd" >> "$GITHUB_ENV"
          SHA=${{ github.sha }}
          echo "IMAGE_TAG=${BRANCH_NAME}-${SHA:0:7}" >> "$GITHUB_ENV"
      - name: Build the Docker image
        run: docker build -t "${IMAGE_NAME}:${IMAGE_TAG}" .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the Docker image
        run: docker push "${IMAGE_NAME}:${IMAGE_TAG}"
      - name: Push the latest Docker image
        if: ${{ github.ref_name == 'main' }}
        run: |
          docker tag "${IMAGE_NAME}:${IMAGE_TAG}" "${IMAGE_NAME}:latest"
          docker push "${IMAGE_NAME}:latest"