name: Build Docker Image

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      converter_image_name: ${{ steps.image_attrs.outputs.converter_name }}
      accounts_image_name: ${{ steps.image_attrs.outputs.accounts_name }}
      image_tag: ${{ steps.image_attrs.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Build apps
        run: mvn clean package

      - name: Set branch name
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> "$GITHUB_ENV"

      - name: Set branch name on PR trigger
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "BRANCH_NAME=${{ github.head_ref }}" >> "$GITHUB_ENV"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set Docker image names and tags
        run: |
          IMAGE_NAME_PREFIX="${{ vars.DOCKERHUB_USERNAME }}/ci_cd"
          echo "IMAGE_INTEGER_ADDER=${IMAGE_NAME_PREFIX}-integer_adder" >> "$GITHUB_ENV"
          echo "IMAGE_RANDOM_NUMBER=${IMAGE_NAME_PREFIX}-random_number" >> "$GITHUB_ENV"
          echo "IMAGE_CONVERTER=${IMAGE_NAME_PREFIX}-converter" >> "$GITHUB_ENV"
          echo "IMAGE_ACCOUNTS=${IMAGE_NAME_PREFIX}-accounts" >> "$GITHUB_ENV"
          SHA=${{ github.sha }}
          echo "IMAGE_TAG=${BRANCH_NAME}-${SHA:0:7}" >> "$GITHUB_ENV"

      - name: Set outputs of image attributes
        id: image_attrs
        run: |
          echo "converter_name=${IMAGE_CONVERTER}" >> "$GITHUB_OUTPUT"
          echo "accounts_name=${IMAGE_ACCOUNTS}" >> "$GITHUB_OUTPUT"
          echo "tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: Build the Docker images
        run: |
          docker build \
          --build-arg JAR_FILE=integer-adder/target/integer-adder.jar \
          -t "${IMAGE_INTEGER_ADDER}:${IMAGE_TAG}" .
          docker build \
          --build-arg JAR_FILE=random-number/target/random-number.jar \
          -t "${IMAGE_RANDOM_NUMBER}:${IMAGE_TAG}" .
          docker build \
          --build-arg JAR_FILE=converter/target/converter.jar \
          -t "${IMAGE_CONVERTER}:${IMAGE_TAG}" .
          docker build \
          --build-arg JAR_FILE=accounts/target/accounts.jar \
          -t "${IMAGE_ACCOUNTS}:${IMAGE_TAG}" .

      - name: Push the Docker images
        run: |
          docker push "${IMAGE_INTEGER_ADDER}:${IMAGE_TAG}"
          docker push "${IMAGE_RANDOM_NUMBER}:${IMAGE_TAG}"
          docker push "${IMAGE_CONVERTER}:${IMAGE_TAG}"
          docker push "${IMAGE_ACCOUNTS}:${IMAGE_TAG}"

      - name: Push the latest Docker images
        if: ${{ github.ref_name == 'main' }}
        run: |
          docker tag "${IMAGE_INTEGER_ADDER}:${IMAGE_TAG}" "${IMAGE_INTEGER_ADDER}:latest"
          docker push "${IMAGE_INTEGER_ADDER}:latest"
          docker tag "${IMAGE_RANDOM_NUMBER}:${IMAGE_TAG}" "${IMAGE_RANDOM_NUMBER}:latest"
          docker push "${IMAGE_RANDOM_NUMBER}:latest"
          docker tag "${IMAGE_CONVERTER}:${IMAGE_TAG}" "${IMAGE_CONVERTER}:latest"
          docker push "${IMAGE_CONVERTER}:latest"
          docker tag "${IMAGE_ACCOUNTS}:${IMAGE_TAG}" "${IMAGE_ACCOUNTS}:latest"
          docker push "${IMAGE_ACCOUNTS}:latest"

  autotest:
    needs: build
    uses: central-university-dev/hse-ab-cicd-hw/.github/workflows/autotests.yml@main
    with:
      chart-path: ./helm-chart
      image-name: ${{ needs.build.outputs.converter_image_name }}
      image-tag: ${{ needs.build.outputs.image_tag }}

  autotest-hw4:
    needs: build
    uses: central-university-dev/hse-ab-cicd-hw/.github/workflows/autotests-hw4.yml@main
    with:
      chart-path: ./helm-chart
      converter-image-name: ${{ needs.build.outputs.converter_image_name }}
      accounts-image-name: ${{ needs.build.outputs.accounts_image_name }}
      image-tag: ${{ needs.build.outputs.image_tag }}
