name: Build Docker Image

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.image_attrs.outputs.name }}
      image_tag: ${{ steps.image_attrs.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Build app
        run: mvn clean package

      - name: Set branch name
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> "$GITHUB_ENV"

      - name: Set branch name on PR trigger
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "BRANCH_NAME=${{ github.head_ref }}" >> "$GITHUB_ENV"

      - name: Set Docker image name and image tag
        run: |
          echo "IMAGE_NAME=${{ vars.DOCKERHUB_USERNAME }}/ci-cd" >> "$GITHUB_ENV"
          SHA=${{ github.sha }}
          echo "IMAGE_TAG=${BRANCH_NAME}-${SHA:0:7}" >> "$GITHUB_ENV"

      - id: image_attrs
        run: |
          echo "name=$IMAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: Build the Docker image
        run: docker build -t "${IMAGE_NAME}:${IMAGE_TAG}" .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push the Docker image
        run: docker push "${IMAGE_NAME}:${IMAGE_TAG}"

      - name: Push the latest Docker image
        if: ${{ github.ref_name == 'main' }}
        run: |
          docker tag "${IMAGE_NAME}:${IMAGE_TAG}" "${IMAGE_NAME}:latest"
          docker push "${IMAGE_NAME}:latest"

  autotest:
    needs: build
    uses: central-university-dev/hse-ab-cicd-hw/.github/workflows/autotests.yml@main
    with:
      chart-path: ./helm-chart
      image-name: ${{ needs.build.outputs.image_name }}
      image-tag: ${{ needs.build.outputs.image_tag }}
