name: Build Docker Image

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print vars
        env:
          tag_prefix: ${{ github.event_name == 'pull_request' && ${{ github.head_ref }} || ${{ github.ref_name }} }}
        run: echo 'Answer is $tag_prefix'

      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build
        run: ./gradlew clean build
      - name: Build the Docker image
        run: docker build --build-arg JAR_FILE=build/libs/\*.jar -t vl4ds4m/integer-adder .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Push the Docker image
        run: |
          docker tag vl4ds4m/integer-adder vl4ds4m/integer-adder:${{ github.ref_name }}-${{ steps.commit.outputs.short }}
          docker push vl4ds4m/integer-adder:${{ github.ref_name }}-${{ steps.commit.outputs.short }}
      - name: Push the latest Docker image
        if: ${{ github.ref_name }} == 'main'
        run: docker push vl4ds4m/integer-adder # pushed with default tag 'latest'