name: Run Docker Container

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        type: string
        required: false
        default: 'latest'
      arg1:
        description: 'First program argument'
        type: string
        required: true
      arg2:
        description: 'Second program argument'
        type: string
        required: true

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Run the Docker container
        run: docker run vl4ds4m/integer-adder:${{ inputs.image_tag }} ${{ inputs.arg1 }} ${{ inputs.arg2 }}