name: Run accounts tests manually

on:
  workflow_dispatch:
    inputs:
      chart_path:
        description: Path to Chart
        required: true
        type: string
      converter_image_name:
        description: Converter Image Name
        required: true
        type: string
      accounts_image_name:
        description: Accounts Image Name
        required: true
        type: string
      image_tag:
        description: Images Tag
        required: false
        type: string
        default: latest

jobs:
  autotest:
    uses: ./.github/workflows/test-accounts.yml
    with:
      chart_path: ${{ inputs.chart_path }}
      converter_image_name: ${{ inputs.converter_image_name }}
      accounts_image_name: ${{ inputs.accounts_image_name }}
      image_tag: ${{ inputs.image_tag }}
    secrets:
      HSE_LOKI_TOKEN: ${{ secrets.HSE_LOKI_TOKEN }}
