name: Run converter tests manually

on:
  workflow_dispatch:
    inputs:
      chart_path:
        description: Path to Chart
        required: true
        type: string
      image_name:
        description: Image Name
        required: true
        type: string
      image_tag:
        description: Images Tag
        required: false
        type: string
        default: latest

jobs:
  autotest:
    uses: ./.github/workflows/test-converter.yml
    with:
      chart_path: ${{ inputs.chart_path }}
      image_name: ${{ inputs.image_name }}
      image_tag: ${{ inputs.image_tag }}
