name: Run converter tests

on:
  workflow_call:
    inputs:
      chart_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Add helm repo
        run: |
          helm repo add cetic https://cetic.github.io/helm-charts
          helm repo update

      - name: Deploy rates
        continue-on-error: true
        run: |
          helm upgrade --install rates ${{ inputs.chart_path }} \
            --set fullnameOverride=rates \
            --set image.repository=miraclewisp/hse-rates \
            --set image.tag=amd64 \
            --set replicaCount=1 \
            --wait --timeout 180s

      - name: Deploy converter
        continue-on-error: true
        run: |
          helm upgrade --install converter ${{ inputs.chart_path }} \
            --set fullnameOverride=converter \
            --set image.repository=${{ inputs.image_name }} \
            --set image.tag=${{ inputs.image_tag }} \
            -f test/k8s/cfg/converter-values.yml \
            --set replicaCount=2 \
            --wait --timeout 180s

      - name: Run tests
        continue-on-error: true
        run: |
          helm install autotest cetic/job \
            --set image.repository=miraclewisp/hse-rates \
            --set image.tag=amd64 \
            --set backoffLimit=0 \
            --set 'args={\"test\"\, \"http://converter:8080\"}' \
            --wait --wait-for-jobs --timeout 180s

      - name: Debug k8s entities
        if: always()
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get services
          kubectl get endpoints rates
          

      - name: Debug logs
        if: always()
        run: |
          kubectl get pods -n default|grep -v NAME|awk '{print $1}'|while read pods;do kubectl logs $pods;echo;done      

      - name: Get test logs
        run: |
          kubectl logs jobs/autotest-job
